'use client'
import { useState } from 'react'

const products = {
  'elise-90-range-cooker': { brand:'AGA', name:'Elise 90 Range Cooker', price:'$4,890', image:'image-oven', description:'A beautifully capable range cooker designed to become the heart of the kitchen.', details:['90cm width','Five gas burners','Two ovens + grill','Two year warranty'] },
  'haven-lounge-chair': { brand:'South Grant Atelier', name:'Haven Lounge Chair', price:'$1,240', image:'image-chair', description:'Deep comfort and quiet character, upholstered in a durable natural weave.', details:['Solid oak frame','Natural linen blend','Hand finished','Made to order'] },
  '50s-style-refrigerator': { brand:'Smeg', name:"50's Style Refrigerator", price:'$2,190', image:'image-fridge', description:'Iconic soft curves and generous everyday storage in a considered finish.', details:['Energy class D','326 litre capacity','MultiFlow cooling','Two year warranty'] },
  'bok-extendable-table': { brand:'Ethnicraft', name:'Bok Extendable Table', price:'$2,895', image:'image-table', description:'An architectural dining table with a light silhouette and room to grow.', details:['Solid oak','Seats 6–10','Natural oil finish','Designed in Belgium'] },
}

export default function ProductPage({ params }) {
  const product = products[params.slug] || products['elise-90-range-cooker']; const [added,setAdded]=useState(false)
  return <><header className="site-header"><nav className="nav container"><a className="brand logo-wrap" href="/" aria-label="South Grant home"><img src="/southgrant-logo.png" alt="South Grant" /></a><ul className="nav-menu"><li><a href="/">New arrivals</a></li><li><a href="/appliances">Appliances</a></li><li><a href="/furniture">Furniture</a></li><li><a href="/collections">Collections</a></li><li><a href="/inspiration">Inspiration</a></li><li><a href="/about">About</a></li></ul><a className="icon-btn" href="/">Bag</a></nav></header><main className="product-detail"><div className={`detail-image product-image ${product.image}`} role="img" aria-label={product.name}/><div className="detail-copy"><a className="back-link" href="/">← Back to shop</a><p className="kicker">{product.brand}</p><h1>{product.name}</h1><p className="detail-price">{product.price}</p><p className="detail-description">{product.description}</p><button className="button button-dark detail-add" onClick={()=>setAdded(true)}>{added ? 'Added to bag ✓' : 'Add to bag'}</button><div className="specs">{product.details.map(detail=><div key={detail}><span>—</span>{detail}</div>)}</div><p className="delivery-note">Complimentary white glove delivery on orders over $2,000.</p></div></main><footer><div className="container footer-top"><a className="brand logo-wrap footer-logo" href="/"><img src="/southgrant-logo.png" alt="South Grant" /></a><p>Considered living for modern homes.</p></div></footer></>
}
